### ISSUE TITLE
Memory Leak with the API

### ISSUE THREAD

**Issue by Benoss** [sethblack/python-seo-analyzer#14]
When using python-seo-analyzer as an API  the memory is never released
That's because

```
wordcount = {}
two_ngram = Counter()
three_ngram = Counter()
pages_crawled = []
pages_to_crawl = []
stem_to_word = {}
stemmer = nltk.stem.porter.PorterStemmer()
page_titles = []
page_descriptions = []

```
are defined globally in analyzer.py

This also prevent from running 2 different analyze() on 2 different sites with the same interpreter.

Suggestion create a Site class that would be instantiated at the beginning of analyze would hold the data and will be released at the end of the function.

**Comment by sethblack** [comment]
@Benoss I absolutely agree. I'll try to get a fix for this in the next few days.

**Comment by sethblack** [comment]
Fixed with https://github.com/sethblack/python-seo-analyzer/commit/32cc0e5681e7acca4abdf216f460198cd5a8c356
