### ISSUE TITLE
Make Page object more independant

### ISSUE THREAD

**Issue by Benoss** [sethblack/python-seo-analyzer#16]
I know it is a bit more longshot, but do you think you could refactor the Page so that a Page object can get the full HTML as a parameter and skip the request.get() in analyze.

I have 2 real use cases for that:

- I have a Django website and I'd like to do a report in the CMS when somebody preview a page. The page is not live yet, but in Django I have access to the rendered HTML. Sending it to the Page could give the writers good insights before an article goes live
- One of my client has an Angular + API website. Because this is a full page app the HTML is just javascript and not returning anything. I can fetch those pages with Javascript rendering using Selenium and chrome driver then extract the DOM and send it to python-seo-analyzer

**Comment by sethblack** [comment]
Fixed in version 4.0.0. A few years late. X_x

**Comment by Benoss** [comment]
Awesome thanks :)
