### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'facebook'

### ISSUE THREAD

**Issue by vmajor** [sethblack/python-seo-analyzer#17]
exits with the error `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'facebook'`

while running a scan with sitemap and html output options.

Ubuntu Xenial running in the Windows 10 environment

**Comment by rtruxal** [comment]
+1

**Comment by rtruxal** [comment]
I straight up cannot figure out what's going wrong either; I'm doing it with the python API & not getting a traceback...  

Also `facebook` only appears twice in analyzer.py, & neither occurance is an attribute lookup.

**Comment by rtruxal** [comment]
Ok so: This **only happens when you use the global `analyze()` function twice in the same program.** Somewhere, something isn't getting deleted.

**Comment by sethblack** [comment]
Nice find @rtruxal! I do have a fork that cleans up a lot of this and some object leaks. I just haven't had a chance to merge it back in. Let me try to knock that out real quick.

**Comment by sethblack** [comment]
https://github.com/sethblack/python-seo-analyzer/commit/32cc0e5681e7acca4abdf216f460198cd5a8c356 should fix it
