### ISSUE TITLE
NameError: name 'k' is not defined

### ISSUE THREAD

**Issue by tvdsluijs** [sethblack/python-seo-analyzer#26]
Hi I get this error on my site (other sites work fine)

```
  File "seo.py", line 49, in __init__
    output = analyze(site, sitemap)
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/analyzer.py", line 546, in analyze
    pg.analyze()
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/analyzer.py", line 218, in analyze
    self.populate(soup_lower)
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/analyzer.py", line 171, in populate
    k))
NameError: name 'k' is not defined
```

**my code**

```
site = "https://vandersluijs.nl"
sitemap = "https://vandersluijs.nl/sitemap_index.xml"
output = analyze(site, sitemap) #line gives error
print(str(output)
```

**Comment by KKONZ** [comment]
I am also getting the same error when attempting to run on a few .edu sites.

**Comment by rocketOC** [comment]
@KKONZ Do you have a few sites and sitemaps that I can reproduce the error with?

**Comment by aalzooke** [comment]
if you are using Keras do the following 
from keras import backend as K

**Comment by rtruxal** [comment]
Try again. The pypi version was 1 version-bump behind. `k` was switched to `keywords`.

@sethblack just fixed. Should work now.

**Comment by KKONZ** [comment]
@rocketOC Sorry for the delayed response. I had tried a few sites in one sitting but didn't actually save any of the work. Sorry I don't have any sitemap examples for you. I want to say that the University of MN site (https://twin-cities.umn.edu/) was one of them!?
