### ISSUE TITLE
feat: Structured JSON Results

### ISSUE THREAD

**Issue by amitgandhinz** [sethblack/python-seo-analyzer#3]
Currently the results are returned partially in JSON for the social stats and list of warnings.  The word stats are then just returned as output without structure.

It would be nice to return all the results in a nice parseable JSON output so that the output can be used to generate GUI's/reports over the top of it.

For Example:
```javascript
{
 {
 "www.site.com/page.html": {
   "social": [ { ... } ]
   "warnings" : [ {...} ]
 },
 {
 "keywords": {
    "apple" : 6,
    "banana": 2,
    "monkey eat banana" : 4
  }
 }
}
```

**Comment by sethblack** [comment]
Good call. I can hack on that this evening.
