### ISSUE TITLE
Runing on localhost:port only crawls home page

### ISSUE THREAD

**Issue by chuksleo** [sethblack/python-seo-analyzer#32]
I installed the library and  every thing seems good i used python 3 on a Linux Ubuntu 16 machine
when i run on  my local instance it only crawls the home page but when i run against my live site http://mysite.com it  crawlies all pages.

**Comment by sethblack** [comment]
Fixed in v4. 👍 Just tested on my box with the test taleas.com site:

```shell
seoanalyze http://localhost:5002
...snip!
"errors": [],
    "total_time": 7.094620943069458,
    "duplicate_pages": [
        [
            "http://localhost:5002",
            "http://localhost:5002/"
        ]
    ]
}
```
