### ISSUE TITLE
feat: SEO ScoreCard

### ISSUE THREAD

**Issue by amitgandhinz** [sethblack/python-seo-analyzer#4]
As a user I would like to see each page scored (A, B, C, F) based on the issues found so that I know where my effort should be focused for On Page SEO Optimization.

**Comment by sethblack** [comment]
Interesting. I'll see what I can do.

**Comment by amitgandhinz** [comment]
thanks.  hope you don't mind me adding a bunch of suggestions.  I will work on some of these as time permits also.  

I really like this tool and was planning to build one myself before coming across this repo.

**Comment by sethblack** [comment]
Welcome. No worries. I built this maybe 5-6 years ago and decided about 3 years ago to release it open source so others could use it, so I'm glad you like it.
