### ISSUE TITLE
Errors on large sites?

### ISSUE THREAD

**Issue by TheWebGuruDotNet** [sethblack/python-seo-analyzer#45]
Hey, great script and works great on small sites, but i guess  i am having issues and not sure if this is related to the size of the site or special characters in there:

File "...programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...Programs\Python\Python38-32\Scripts\seoanalyze.exe\__main__.py", line 7, in <module>
  File "...\appdata\local\programs\python\python38-32\lib\site-packages\seoanalyzer\__main__.py", line 35, in main
    print(output_from_parsed_template)
  File "...\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ea5' in position 1179652: character maps to <undefined>

**Comment by sethblack** [comment]
Hiya! Thanks. :)

Looks like special characters to me. \u1ea5 looks like an extended Latin character.

ấ
--


ấ
--

**Comment by TheWebGuruDotNet** [comment]
Oh thanks for getting back
it does exist (check attached screenshot)
how is it possible to bypass these and generate the html? 

![Screaming Frog Results](https://user-images.githubusercontent.com/56264102/67568939-77f66d80-f725-11e9-8b31-8eae2836f70c.jpg)

**Comment by sethblack** [comment]
No problem.

Hmm. May need to do some more decoding. Let me take a look in a few hours and I'll get back to you.

**Comment by TheWebGuruDotNet** [comment]
Than would be great as i guess many websites will have this issue Seth.
Great futuristic work though! 
Cheers

**Comment by sethblack** [comment]
Heyo, I'm still working on this. I have a new branch working and am adding some tests so I can track down unicode issues in the future.

Thank you!

**Comment by TheWebGuruDotNet** [comment]
Your Script, your time :)
but i really think this thing has a future and can be turned into a big project!
Cheers

**Comment by sethblack** [comment]
Ha! True. I try to put aside some time every month to hack on it.

I _think_ this is fixed in 3.1.4 now. Let me know if you're still having issues.

**Comment by TheWebGuruDotNet** [comment]
OW Awesome, i will sure get back to you when i find some time MYSELF for this!
cheers for the efforts. post these changes to log as they are pretty important

**Comment by sethblack** [comment]
Heyo @TheWebGuruDotNet would you mind testing this in v4.0.0? Just did a major refactor.

**Comment by TheWebGuruDotNet** [comment]
Hey, i will get to this as soon as i can, i am smashed with things these days!
i will sure let you know once i test this

**Comment by sethblack** [comment]
No worries at all, I totally understand. If it's still an issue, I'll re-open this issue. 👍

**Comment by brentvollebregt** [comment]
I've also come across the same issue with the error:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 2640018: character maps to <undefined>
```

That character does exist, and this tool has brought the existence of it to my attention, so it's not an issue for me but I felt it would be still ideal to report.

It is still coming from the `print(output_from_parsed_template)` statement on line 35 in seoanalyzer\__main__.py. Here is a the trace:

```
(venv) C:\Users\Brent\Development\TestingEnvironment>seoanalyze http://192.168.1.181:8000/ --sitemap http://192.168.1.181:8000/sitemap.xml -f html > output.html
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Brent\Development\TestingEnvironment\venv\Scripts\seoanalyze.exe\__main__.py", line 9, in <module>
  File "C:\Users\Brent\Development\testingenvironment\venv\lib\site-packages\seoanalyzer\__main__.py", line 35, in main
    print(output_from_parsed_template)
  File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 2640018: character maps to <undefined>
```

**Comment by sethblack** [comment]
Wow. Strange. @brentvollebregt does it throw the same error if you output json instead of html?

**Comment by brentvollebregt** [comment]
No, I executed:

```
seoanalyze http://192.168.1.181:8000/ --sitemap http://192.168.1.181:8000/sitemap.xml -f json > output.json
```

and output.json was written to. The \ufeff character does not appear in this file.

**Comment by sethblack** [comment]
Cool, that gives me something to go off of. Thank you! There may be something up when passing the dataset to jinja. I'll dig around and see if I can get this patched for ya.
