### ISSUE TITLE
Replace the template 

### ISSUE THREAD

**Issue by lzomedia** [sethblack/python-seo-analyzer#46]
Is there any way that will allow me to replace the index.html with my own template or do I need to export as JSON and play with that ?

**Comment by sethblack** [comment]
That is a fantastic idea. I'm fighting with an encoding but currently, but I can roll in a dynamic template loader too.

The easiest way right now would be to clone the repo and modify the template in seoanalyzer/templates directly.

**Comment by lzomedia** [comment]
Thanks for the fast feedback,
for now I've decided to use the JSON stuff and i will pipe it to my PHP script 
I think this can be moved to a future request and have people vote for it

**Comment by sethblack** [comment]
No problem. Cool, that sounds like a plan.
