### ISSUE TITLE
Traceback errors, seoanalyze won't run

### ISSUE THREAD

**Issue by ctrlbrk42** [sethblack/python-seo-analyzer#57]
02:21 PM [pilot]~ root # seoanalyze
Traceback (most recent call last):
  File "/usr/local/bin/seoanalyze", line 7, in <module>
    from seoanalyzer.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/__init__.py", line 3, in <module>
    from .analyzer import analyze
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/analyzer.py", line 5, in <module>
    from seoanalyzer.website import Website
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/website.py", line 9, in <module>
    from seoanalyzer.page import Page
  File "/usr/local/lib/python3.5/dist-packages/seoanalyzer/page.py", line 128
    self.warn(f'Keywords should be avoided as they are a spam indicator and no longer used by Search Engines: {keywords}')
                                                                                                                        ^
SyntaxError: invalid syntax

02:21 PM [pilot]~ root # pip3 install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.6.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests==2.20.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Jinja2==2.10.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: urllib3==1.24.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: certifi==2018.11.29 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests==2.20.0->-r requirements.txt (line 2))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests==2.20.0->-r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2==2.10.1->-r requirements.txt (line 3))

**Comment by sethblack** [comment]
Hiya! Looks like you're running Python 3.5. You need at least Python 3.6 to run the analyzer.
