### ISSUE TITLE
No file gets output?

### ISSUE THREAD

**Issue by matija2209** [sethblack/python-seo-analyzer#73]
No matter what I do, no file gets output.  `seoanalyze -f html https://x.com`

The script seems to do what it needs as the data is printed in the terminal but no file is being created.

**Comment by SamPetherbridge** [comment]
@matija2209 You will need to pipe this into a file. On a Mac, this is done by appending ` > results.html` to the end so the command would be `seoanalyze -f html https://x.com > results.html`
