### ISSUE TITLE
Trying to pull Docker image sethblack/python-seo-analyzer gives error "repository does not exist"

### ISSUE THREAD

**Issue by alberto56** [sethblack/python-seo-analyzer#87]
**Describe the bug**

The [README](https://github.com/sethblack/python-seo-analyzer#docker) says this can be used with Docker:

    docker run sethblack/python-seo-analyzer [ARGS ...]

However, that image does not exist.

**To Reproduce**

    $ docker pull sethblack/python-seo-analyzer           
    Using default tag: latest
    Error response from daemon: pull access denied for sethblack/python-seo-analyzer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Expected behavior**

Docker image should either exist, or the README should not contain Docker information.

**Desktop (please complete the following information):**

 - OS: macOS

**Comment by sethblack** [comment]
Yep, looks like the image was privatized and pruned a couple of years ago. This has been fixed and the latest version has been added to DockerHub.
